// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywmkycemozecroohrisr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3bWt5Y2Vtb3plY3Jvb2hyaXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MzQ2MjAsImV4cCI6MjA2MTMxMDYyMH0.2H1p4PZcg_fVpjcmwrreE0z3ZEaQQrv_VzC1gERQagM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);